//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseDB
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Artist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artist()
        {
            this.Paintings = new ObservableCollection<Painting>();
        }
    
        public int id { get; set; }
        public string full_name { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public Nullable<System.DateTime> date_of_death { get; set; }
        public string biography { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Painting> Paintings { get; set; }
    }
}
