//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseDB
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Exhibit
    {
        public int painting_id { get; set; }
        public System.DateTime date_of_acquiring { get; set; }
        public bool is_original { get; set; }
        public int width { get; set; }
        public int height { get; set; }
        public string canvas_type { get; set; }
        public string paint_type { get; set; }
        public int hall_id { get; set; }
    
        public virtual Hall Hall { get; set; }
        public virtual Painting Painting { get; set; }
    }
}
