//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseDB
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Painting
    {
        public int id { get; set; }
        public string name { get; set; }
        public int artist_id { get; set; }
        public Nullable<int> year_of_creation { get; set; }
        public byte[] image { get; set; }
        public int art_movement_id { get; set; }
    
        public virtual Art_movement Art_movement { get; set; }
        public virtual Artist Artist { get; set; }
        public virtual Exhibit Exhibit { get; set; }
    }
}
