//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseDB
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class User_profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_profile()
        {
            this.Tickets = new ObservableCollection<Ticket>();
        }
    
        public string user_login { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public bool is_admin { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Ticket> Tickets { get; set; }
    }
}
